language: node_js
node_js:
  - "8"
  - "9"
brancher:
  only:
    - "dev"
    - "master"
install:
  - "npm install --prefix ./Testing"
  - "npm install -g codecov"
script:
  - "npm run cover --prefix ./Testing"
  - "codecov"